
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.pg.username %>
  password: <%= Rails.application.credentials.pg.password %>
  host: <%= Rails.application.credentials.pg.host %>
  port: <%= Rails.application.credentials.pg.port %>
development:
  <<: *default
  database: ticket_app_development

test:
  <<: *default
  database: ticket_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
